[package]
name = "rpc"
version = "0.1.0"
edition = "2021"
authors = ["Kovas McCann <KovasMcCann@firemail.cc>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
